version: '3'
services:
  go_practice:
    build: 
      context: .
      dockerfile: ./go_practice/Dockerfile
    container_name: go_practice
    # コンテナの永続化
    tty: true
    volumes:
      - ./go_practice:/go/src/go_practice
    ports:
      - 8080:8080
